# Uncomment the next line to define a global platform for your project
platform :ios, ‘8.0’

target 'AAR Diagnostic Tool' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AAR Diagnostic Tool
  

  target 'AAR Diagnostic ToolTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AAR Diagnostic ToolUITests' do
    inherit! :search_paths
    # Pods for testing
  
  end

end
